server:
  port: 1111
  servlet:
    context-path: /api
logging:
  pattern:
    level: "%5p [${spring.application.name:}] tenantId=%X{tenantId:-}"
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://oneshoot.local:9999/realms/OneShoot}
  application:
    name: tenantService
  servlet:
    multipart:
      max-file-size: 100MB  # 2MB/file (50files) = 100MB                { linkedIn profile PDF 50kb-100kb --> 100MB support 1000 files  }
      max-request-size: 100MB  # 2MB/file (50files) = 100MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/tenantService?useSSL=false&serverTimezone=GMT&createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: oneshootapplication@gmail.com
    password: rlsyhauozwxkdvtc # expired no worries :)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  #flyway:
  #  enabled: true
  #  locations: classpath:db/migration
  #  user: admin           # to tell spring boot to create a separate connection for applying the migration
  #  password: the_secured_password

keycloak:
  realm: OneShoot
  serverUrl: http://localhost:9999/
  adminClientId: admin-cli
  adminClientSecret: yHUjXfiq3zvscHyNQX9ovrj4CizTqE2x
  client: tenant-service
